<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Context\" />
    <Folder Include="Configurations\" />
    <Folder Include="Migrations\" />
    <Folder Include="UnitOfWork\" />
    <Folder Include="Seed\" />
    <Folder Include="Repositories\Interfaces\" />
    <Folder Include="Repositories\Implementations\" />
  </ItemGroup>

</Project>
